### ISSUE TITLE
Document whether each Trajectory supports CUDA.jl or not

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearningTrajectories.jl#3]

**Comment by ludvigk** [comment]
NStepBatchSampler and BatchSampler return non-contiguous SubArrays for state and next_state, which have to be collected before being transferred to the gpu. This seems to be very slow. Will incorporating the old `consecutive_view` function help with this issue?

**Comment by findmyway** [comment]
> Will incorporating the old consecutive_view function help with this issue?

I'm afraid not. If I remember it correctly,  the old `consecutive_view` also has the same issue.

The best we can do here is to reuse the collected array buffer instead of allocating a new one every time.

**Comment by ludvigk** [comment]
Yeah, I thought about that. Right now, it’s easy to do on the policy side, but it seems like a feature that is better to keep on the trajectory side of things. Question is if there are some algorithms that won’t benefit from a contiguous array, and thus getting an unnecessary slowdown from transferring the data to the contiguous array buffer. Perhaps it would be worth sacrificing those algorithms (if they exist) for the convenience factor?

**Comment by findmyway** [comment]
>  Question is if there are some algorithms that won’t benefit from a contiguous array, and thus getting an unnecessary slowdown from transferring the data to the contiguous array buffer.

This can be made pluggable. I may add an example soon.
